name: Deploy to AzureVM
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to AzureVM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/azureuser/server
          sudo rm -rf User-Server
          git clone https://github.com/BharatSeva/User-Server.git
          sudo docker rm -f client_server || true
          sudo docker-compose up -d --build

          sudo docker exec -it nginx nginx -s reload
